spring:
  profiles:
    active: dev2
  
  jpa:
    hibernate:
      ddl-auto: update

---
spring:
  profiles: prod
  datasource:
    url: jdbc:h2:file:/C://temp/springdb
    username: admin
    password:
    drive-class-name: org.h2.Driver
---
spring:
  profiles: dev
  datasource:
    url: jdbc:h2:mem:springbootdb
    username: admin
    password: 1234
    drive-class-name: org.h2.Driver
---
spring:
  profiles: dev2
  datasource:
    url: jdbc:h2:file:/C://temp/springdb2
    username: admin
    password: 1234
    drive-class-name: org.h2.Driver